version: "3"

services:
  architectural-grc:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./:/app
    networks:
      - architectural-grc-net

networks:
  architectural-grc-net:
    driver: bridge

volumes:
  pgdata: